### ISSUE TITLE
onColorSelected prototype claims (color: HsvColor) arg, but it's actually (color: string)

### ISSUE THREAD

**Issue by seasox** [instea/react-native-color-picker#18]
The exported IPicker interface has HsvColor as argument for onColorSelected: `onColorSelected: (selectedColor: HsvColor) => void;`
But the argument is actually a string (`tinycolor(...).toHexString()`), which makes TypeScript sad. Will file a PR later this week.

Merry Christmas!

**Comment by sodik82** [comment]
thanks

**Comment by sodik82** [comment]
should be fixed in '0.5.0'
