### ISSUE TITLE
Color picker shrinks automatically on android every time keyboard comes up.

### ISSUE THREAD

**Issue by dayoul** [instea/react-native-color-picker#24]
![스크린샷 2020-03-28 오후 1 38 01](https://user-images.githubusercontent.com/62198393/77815035-ee92ff00-70f9-11ea-9f2c-ada689383a93.png)
![스크린샷 2020-03-28 오후 1 37 31](https://user-images.githubusercontent.com/62198393/77814989-86441d80-70f9-11ea-8cb5-f83841877ceb.png)

First of all, I did not use and 'KeyboardAvoingView'. So on iOS, Color picker circle remains same even if the keyboard comes up. But on android, color circle shrinks to avoid the keyboard. 
But I want the color circle to remain same at the origin place even if the keyboard comes up.

Any solutions for this?

Thank you very much!

**Comment by sodik82** [comment]
color picker always use all the space provided.... so its container must have been shrunk. Fixing the height could be a quick-fix or you have to find out why it shrinks (maybe checkout android:windowSoftInputMode in your android manifest).

**Comment by dayoul** [comment]
> color picker always use all the space provided.... so its container must have been shrunk. Fixing the height could be a quick-fix or you have to find out why it shrinks (maybe checkout android:windowSoftInputMode in your android manifest).

Thanks I'll check on that!
