### ISSUE TITLE
sliderComponent

### ISSUE THREAD

**Issue by cristea2017** [instea/react-native-color-picker#27]
I have error when i try to add sliderComponent

My code :

` <ColorPicker
                        onColorSelected={color => alert(`Color selected: ${color}`)}
                        style={{ flex: 1 }}
                        color={this.state.color}
                        onColorChange={this.onColorChange}
                        sliderComponent={<Slider
                            style={{ width: 200, height: 40 }}
                            minimumValue={0}
                            maximumValue={10}
                            minimumTrackTintColor="#FFFFFF"
                            maximumTrackTintColor="#000000"
                        />}
                    />
`

I get this error : 

> element type is invalid expected a string (for built-in components) or a class/function but got objec.

According code of [https://github.com/instea/react-native-color-picker/blob/master/src/HoloColorPicker.js](url) ,
sliderComponent is of type 'PropTypes.elementType' where PropType is a npm library 
[https://www.npmjs.com/package/prop-types](url) 

So on prop-types library documentation is indicated that 

`// A React element type (ie. MyComponent).
  optionalElementType: PropTypes.elementType,
`
So i am doing wrong , please help

**Comment by sodik82** [comment]
the problem is that you try to pass ReactElement instead of ReactCompoment....

define your own slider component somewhere else like this

```
const MySlider = (props) => <Slider .... />
```

and then use it `sliderComponent={MySlider}`

**Comment by cristea2017** [comment]
> problem is that you try to pass ReactElement instead of ReactCompoment....
> 
> define your own slider component somewhere else l

Thanks a lot  ;)
