### ISSUE TITLE
Customize colorPreview button/s in TriangleColorPicker

### ISSUE THREAD

**Issue by dmko1610** [instea/react-native-color-picker#28]
### Hi there!
Could you please add ability (if it is possible) to customize these **(colorPreview new and old)** buttons.
As I see this — it can be a style prop for example.
And maybe it is necessary to add some sorta placeholder to the button, because right now it is not clear what this colored square thing do.

I attached example of what I'd want to see
![image](https://user-images.githubusercontent.com/42618412/88063787-7dc99400-cb7b-11ea-89cc-a253893843ea.png)

Thanks in advance!

**Comment by sodik82** [comment]
hm... currently you can't. I believe the best way would be to add new property like `hideButtons` (similar to `hideSliders`). and then you could implement the buttons in any way.

anyone interested in PR?

**Comment by dmko1610** [comment]
> hm... currently you can't. I believe the best way would be to add new property like `hideButtons` (similar to `hideSliders`). and then you could implement the buttons in any way.
> 
> anyone interested in PR?
I was interested
https://github.com/instea/react-native-color-picker/pull/29

**Comment by dmko1610** [comment]
If nobody mind, I'll close this issue
