### ISSUE TITLE
custom button and props for TriangleColorPicker

### ISSUE THREAD

**Issue by dmko1610** [instea/react-native-color-picker#31]
Hello there, I implemented some feature described here #28 for TriangleColorPicker
Could somebody apply this #29?

**Comment by dmko1610** [comment]
@sodik82, could you help with this, please?

**Comment by sodik82** [comment]
hi there,

you can now (`0.5.3`) simply hide default buttons and render your buttons outside of the component. I believe it should be enough to cover your case.

if not, pls let me know.

**Comment by dmko1610** [comment]
@sodik82, thank you.
